--- #dev
spring:
  profiles: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 123
            client-secret: '!@#'
            scope: profile, email
          github:
            client-id: 456
            client-secret: '$%^'
          kakao:
            client-id: 789
            client-secret: '&*('
server:
  port: 80
logging:
  level:
    root: info
security:
  jwt:
    issuer: dev
    exprTime: 600000 #10분=600초
