# common config
application:
  version: 1.0.0
  title: MemberManager

spring:
  profiles:
    active: local

  thymeleaf:
#    view-names: thymeleaf/*
    prefix: classpath:templates/
    suffix: .html
    cache: false

#  JavaConfig로 설정하여 주석처리함
#  datasource:
#    url: jdbc:h2:~/test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current-session-context-class: org.springframework.orm.hibernate5.SpringSessionContext
      dialect: org.hibernate.dialect.H2Dialect


--- #local
spring:
  profiles: local
server:
  port: 8080
logging:
  level:
    root: debug

--- #dev
spring:
  profiles: dev
server:
  port: 80
logging:
  level:
    root: info

--- #prod
spring:
  profiles: prod
server:
  port: 80
logging:
  level:
    root: error
