--- #prod
spring:
  profiles: prod
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 123
            client-secret: '!@#'
            scope: profile, email
          github:
            client-id: 456
            client-secret: '$%^'
          kakao:
            client-id: 789
            client-secret: '&*('
server:
  port: 80
logging:
  level:
    root: error
security:
  jwt:
    issuer: playground
    exprTime: 1800000 #30분=1800초
