# common config
application:
  version: 1.0.0
  title: MemberManager

spring:
  profiles:
    active: local

  thymeleaf:
#    view-names: thymeleaf/*
    prefix: classpath:templates/
    suffix: .html
    cache: false

  datasource:
    hikari:
      primary:
        jdbc-url: jdbc:h2:~/test
        driver-class-name: org.h2.Driver
        username: sa
        password:
      secondary:
        jdbc-url: jdbc:h2:~/playground
        driver-class-name: org.h2.Driver
        username: sa
        password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current-session-context-class: org.springframework.orm.hibernate5.SpringSessionContext
      dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false


--- #local
spring:
  profiles: local
server:
  port: 8080
logging:
  level:
    root: debug
security:
  jwt:
    issuer: local
    exprTime: 600000 #10분=600초
  oauth:
    google:
      clientId: 451544914380-m657ri1nr9i2b1qeq8jb8p3o3bl1o8b0.apps.googleusercontent.com
      clientSecret: OJ5e5rg1dMVdKsXNKyZQxCqZ
    github:
      clientId: 2c1347aac22bb89c84f3
      clientSecret: 584fdfa0482457ad624a13042e8cf9e3817644da
    kakao:
      clientId: edb60a1796c20a7eab7c98b12c550998
      clientSecret: ixKsmExJxEXAyJMQenZlz9DmdkVeLeSI

--- #dev
spring:
  profiles: dev
server:
  port: 80
logging:
  level:
    root: info
security:
  jwt:
    issuer: dev
    exprTime: 600000 #10분=600초
  oauth:
    google:
      clientId: 451544914380-m657ri1nr9i2b1qeq8jb8p3o3bl1o8b0.apps.googleusercontent.com
      clientSecret: OJ5e5rg1dMVdKsXNKyZQxCqZ
    github:
      clientId: 2c1347aac22bb89c84f3
      clientSecret: 584fdfa0482457ad624a13042e8cf9e3817644da
    kakao:
      clientId: edb60a1796c20a7eab7c98b12c550998
      clientSecret: ixKsmExJxEXAyJMQenZlz9DmdkVeLeSI

--- #prod
spring:
  profiles: prod
server:
  port: 80
logging:
  level:
    root: error
security:
  jwt:
    issuer: playground
    exprTime: 1800000 #30분=1800초
  oauth:
    google:
      clientId: 451544914380-m657ri1nr9i2b1qeq8jb8p3o3bl1o8b0.apps.googleusercontent.com
      clientSecret: OJ5e5rg1dMVdKsXNKyZQxCqZ
    github:
      clientId: 2c1347aac22bb89c84f3
      clientSecret: 584fdfa0482457ad624a13042e8cf9e3817644da
    kakao:
      clientId: edb60a1796c20a7eab7c98b12c550998
      clientSecret: ixKsmExJxEXAyJMQenZlz9DmdkVeLeSI
